title: Christine Africa
logo: /images/pic.png
#logo: /assets/img/headshot_circle.png
description: BS in Information Technology | Quezon City University**  
africa.christine.delluta@gmail.com  
0930-424-9141  
#show_downloads: true
theme: jekyll-theme-minimal
