title: Christine Africa
logo: /images/pic.png
description: BS in Information Technology | Quezon City University  
description: 09304249141
description: africa.christine.delluta@gmail.com
description: Quezon City, Metro Manila, Philippines
show_downloads: true
theme: jekyll-theme-minimal
